#!/usr/bin/env bash
# Build console_wasm → static/pkg (wasm-bindgen glue only; no product JS).
set -euo pipefail
cd "$(dirname "$0")/.."
rustup target add wasm32-unknown-unknown >/dev/null
cargo build -p console_wasm --target wasm32-unknown-unknown --release
WASM="target/wasm32-unknown-unknown/release/console_wasm.wasm"
mkdir -p static/pkg
wasm-bindgen --target web --out-dir static/pkg --out-name console_wasm "$WASM"
# Generated-only bootstrap (no product logic)
cat > static/pkg/boot.js << 'EOF'
/* GENERATED by scripts/build-wasm.sh — do not hand-edit */
import init from "./console_wasm.js";
init();
EOF
echo "# GENERATED — run scripts/build-wasm.sh" > static/pkg/GENERATED.md
echo "OK: static/pkg/console_wasm.js + .wasm + boot.js"
